[package]
name = "win-timer"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["utilapiset"] }

[dependencies]
tui = "0.19.0"
crossterm = "0.25"
